---
apiVersion: v1
kind: ConfigMap
metadata:
  name: psql-config
  labels:
    app: psql-app

data:
  POSTGRES_DB: testdatabase
  POSTGRES_USER: testuser
  PGDATA: /var/lib/postgresql/data/pgdata

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redmine-config
  labels:
    app: redmine-app

data:
  REDMINE_DB_POSTGRES: database
  REDMINE_DB_USERNAME: testuser
  REDMINE_DB_DATABASE: testdatabase