---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: psql-dbstorage
  labels:
    app: psql-app
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-ceph-hdd-dp1