---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redmine
spec:
  strategy: 
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: redmine-app
  template:
    metadata:
      labels:
        app: redmine-app
    spec:
      containers:
      - name: redmine-411
        image: redmine:4.1.1
        ports:
        - name: redmine-port
          containerPort: 3000
        envFrom:
          - configMapRef:
              name: redmine-config
        env:
          - name: REDMINE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: psql-secret
                key: POSTGRES_PASSWORD
          - name: REDMINE_SECRET_KEY_BASE
            valueFrom:
              secretKeyRef:
                name: redmine-secret
                key: REDMINE_SECRET_KEY_BASE

