---
apiVersion: v1
kind: Secret
metadata:
  name: psql-secret
  labels:
    app: psql-app
type: Opaque
data:
  POSTGRES_PASSWORD: dGVzdHBhc3N3b3Jk

---
apiVersion: v1
kind: Secret
metadata:
  name: redmine-secret
  labels:
    app: redmine-app
type: Opaque
data:
  #REDMINE_DB_PASSWORD: dGVzdHBhc3N3b3Jk
  REDMINE_SECRET_KEY_BASE: c3VwZXJzZWNyZXRrZXk=