---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: psql-app
spec:
  type: NodePort
  ports:
   - port: 5432
  selector:
   app: psql-app

---
apiVersion: v1
kind: Service
metadata:
  name: redmine-service
  labels:
    app: redmine-app
spec:
  type: NodePort
  ports:
   - port: 3000
  selector:
   app: redmine-app