apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: psql-app

data:
  POSTGRES_DB: testdatabase
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword
  PGDATA: /var/lib/postgresql/data/pgdata